<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Transaction;
use App\Models\User;
use Carbon\Carbon;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'income' => ['sales', 'service', 'consulting', 'subscription', 'investment'],
            'expense' => ['salary', 'rent', 'utilities', 'marketing', 'equipment', 'supplies', 'travel', 'maintenance']
        ];

        $paymentMethods = ['cash', 'bank_transfer', 'credit_card', 'check'];
        
        $vendors = ['PT ABC Technology', 'CV XYZ Services', 'PT Maju Jaya', 'UD Sejahtera', 'PT Global Solutions'];
        
        $descriptions = [
            'income' => [
                'sales' => 'Penjualan produk SmartPager 2000',
                'service' => 'Jasa instalasi sistem IoT',
                'consulting' => 'Konsultasi implementasi smart factory',
                'subscription' => 'Pembayaran langganan bulanan',
                'investment' => 'Return investasi proyek'
            ],
            'expense' => [
                'salary' => 'Gaji karyawan bulan {month}',
                'rent' => 'Sewa kantor bulan {month}',
                'utilities' => 'Listrik dan air bulan {month}',
                'marketing' => 'Biaya promosi digital marketing',
                'equipment' => 'Pembelian peralatan kantor',
                'supplies' => 'Pembelian supplies operasional',
                'travel' => 'Biaya perjalanan dinas',
                'maintenance' => 'Maintenance server dan infrastruktur'
            ]
        ];

        // Generate transactions for last 3 months
        $startDate = Carbon::now()->subMonths(3)->startOfDay();
        $endDate = Carbon::now()->endOfDay();

        $this->command->info('Generating transactions...');
        
        $currentDate = $startDate->copy();
        while ($currentDate <= $endDate) {
            // Random 1-5 transactions per day
            $transactionsPerDay = rand(1, 5);
            
            for ($i = 0; $i < $transactionsPerDay; $i++) {
                $type = rand(0, 1) ? 'income' : 'expense';
                $category = $categories[$type][array_rand($categories[$type])];
                $description = $descriptions[$type][$category];
                
                if (strpos($description, '{month}') !== false) {
                    $description = str_replace('{month}', $currentDate->format('F Y'), $description);
                }
                
                $amount = 0;
                if ($type === 'income') {
                    // Income between 5 juta - 50 juta
                    $amount = rand(5000000, 50000000);
                } else {
                    // Expense between 1 juta - 20 juta
                    $amount = rand(1000000, 20000000);
                }
                
                Transaction::create([
                    'type' => $type,
                    'category' => $category,
                    'description' => $description,
                    'amount' => $amount,
                    'transaction_date' => $currentDate->format('Y-m-d'),
                    'reference_number' => 'TRX-' . $currentDate->format('Ymd') . '-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT),
                    'vendor_customer' => $type === 'expense' ? $vendors[array_rand($vendors)] : null,
                    'payment_method' => $paymentMethods[array_rand($paymentMethods)],
                    'notes' => 'Generated by seeder for testing purposes',
                ]);
            }
            
            $currentDate->addDay();
        }

        $this->command->info('Transaction seeding completed!');
        $this->command->info('Generated transactions from ' . $startDate->format('Y-m-d') . ' to ' . $endDate->format('Y-m-d'));
    }
}
